#ifndef MESSAGE_H
#define MESSAGE_H

//Getter/setters
#include <QJsonObject>
#include <QJsonArray>
#include <QDateTime>
#include <QString>
#include <QVariant>

#include "chat.h"
#include "user.h"
#include "messageentity.h"
#include "audio.h"
#include "document.h"
#include "game.h"
#include "photosize.h"
#include "sticker.h"
#include "video.h"
#include "voice.h"
#include "videonote.h"
#include "invoice.h"
#include "successfulpayment.h"

class Message
{
public:
    Message(QJsonObject obj);
    Message();
    
    static Message fromObject(QJsonObject obj);
    
    //Getter/setters (Auto generated by Refactor tool)
    
    long long getMessageId() const;
    void setMessageId(long long value);
    
    long long getForwardFromMessageId() const;
    void setForwardFromMessageId(long long value);
    
    long long getMigrateToChatId() const;
    void setMigrateToChatId(long long value);
    
    long long getMigrateFromChatId() const;
    void setMigrateFromChatId(long long value);
    
    bool getDeleteChatPhoto() const;
    void setDeleteChatPhoto(bool value);
    
    bool getGroupChatCreated() const;
    void setGroupChatCreated(bool value);
    
    bool getSupergroupChatCreated() const;
    void setSupergroupChatCreated(bool value);
    
    bool getChannelChatCreated() const;
    void setChannelChatCreated(bool value);
    
    QString getForwardSignature() const;
    void setForwardSignature(const QString &value);
    
    QString getAuthorSignature() const;
    void setAuthorSignature(const QString &value);
    
    QString getText() const;
    void setText(const QString &value);
    
    QString getCaption() const;
    void setCaption(const QString &value);
    
    QString getNewChatTitle() const;
    void setNewChatTitle(const QString &value);
    
    QDateTime getDate() const;
    void setDate(const QDateTime &value);
    
    QDateTime getForwardDate() const;
    void setForwardDate(const QDateTime &value);
    
    QDateTime getEditDate() const;
    void setEditDate(const QDateTime &value);
    
    User getFrom() const;
    void setFrom(const User &value);
    
    User getForwardFrom() const;
    void setForwardFrom(const User &value);
    
    User *getNewChatMembers() const;
    void setNewChatMembers(User *value);
    
    User *getLeftChatMembers() const;
    void setLeftChatMembers(User *value);
    
    Chat getChat() const;
    void setChat(const Chat &value);
    
    Chat getForwardFromChat() const;
    void setForwardFromChat(const Chat &value);
    
    Message getReplyToMessage() const;
    void setReplyToMessage(const Message &value);
    
    Message getPinnedMessage() const;
    void setPinnedMessage(const Message &value);
    
    MessageEntity *getEntities() const;
    void setEntities(MessageEntity *value);
    
    Audio getAudio() const;
    void setAudio(const Audio &value);
    
    Document getDocument() const;
    void setDocument(const Document &value);
    
    Game getGame() const;
    void setGame(const Game &value);
    
    PhotoSize *getPhoto() const;
    void setPhoto(PhotoSize *value);
    
    PhotoSize *getNewChatPhoto() const;
    void setNewChatPhoto(PhotoSize *value);
    
    Sticker getSticker() const;
    void setSticker(const Sticker &value);
    
    Video getVideo() const;
    void setVideo(const Video &value);
    
    Voice getVoice() const;
    void setVoice(const Voice &value);
    
    VideoNote getVideoNote() const;
    void setVideoNote(const VideoNote &value);
    
    Invoice getInvoice() const;
    void setInvoice(const Invoice &value);
    
    SuccessfulPayment getSuccessfulPayment() const;
    void setSuccessfulPayment(const SuccessfulPayment &value);
    
private:
    long long int messageId;
    long long int forwardFromMessageId;
    long long int migrateToChatId;
    long long int migrateFromChatId;
    
    bool deleteChatPhoto;
    bool groupChatCreated;
    bool supergroupChatCreated;
    bool channelChatCreated;
    
    QString forwardSignature;
    QString authorSignature;
    QString text;
    QString caption;
    QString newChatTitle;
    
    QDateTime date;
    QDateTime forwardDate;
    QDateTime editDate;
    
    User from;
    User forwardFrom;
    User *newChatMembers;
    User *leftChatMembers;
    
    Chat chat;
    Chat forwardFromChat;
    
    Message replyToMessage;
    Message pinnedMessage;
    
    MessageEntity *entities;
    Audio audio;
    Document document;
    Game game;
    PhotoSize *photo;
    PhotoSize *newChatPhoto;
    Sticker sticker;
    Video video;
    Voice voice;
    VideoNote videoNote;
    Invoice invoice;
    SuccessfulPayment successfulPayment;
    
    QJsonObject root;
};

#endif // MESSAGE_H
